Webstore/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Webstore.Domain.Entity;
using Webstore.Domain.ViewModel.Product;
using Webstore.Service.Interfaces;

namespace Webstore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        [HttpGet]
        public IActionResult ReadProducts()
        {
            var response = _productService.ReadProducts();
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            return View("Error", $"{response.Description}");
        }

        [HttpGet]
        public async Task<IActionResult> ReadProductById(Guid id)
        {
            var response = await _productService.ReadProductByID(id);
            return PartialView("ReadProduct", response.Data);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteProduct(Guid id)
        {
            var response = await _productService.DeleteProduct(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return RedirectToAction("ReadProducts");
            }
            return View("Error", $"{response.Description}");
        }
        

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Save(Guid id)
        {
            if (id == Guid.Empty)
            {
                return PartialView();
            }

            var response = await _productService.ReadProductByID(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return PartialView(response.Data);
            }
            ModelState.AddModelError("Error", response.Description);
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> Save(ProductViewModel product)
        {
            if (ModelState.IsValid)
            {
                if (product.Id_product == Guid.Empty || product.Id_product == null)
                {
                    await _productService.CreateProduct(product);
                }
                else
                {
                    await _productService.UpdateProduct(product.Id_product, product);
                }
                return RedirectToAction("ReadProducts");
            }
            return View();
        }
    }

}

Webstore/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Webstore.Domain.Entity;
using Webstore.Domain.Helper;
using Webstore.Domain.ViewModel.User;
using Webstore.Service.Interfaces;

namespace Webstore.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Register() => View();

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _userService.Register(model);
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(response.Data));

                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("Error", response.Description);
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Login() => View();

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _userService.Login(model);
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(response.Data));
                    List<Item> items = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                    for (var i = 0; i < items?.Count; i++)
                    {
                        items.RemoveAt(i);
                    }
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", items);
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("Error", response.Description);
            }
            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            List<Item> items = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (var i = 0; i < items?.Count; i++)
            {
                items.RemoveAt(i);
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", items);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Update()
        {
            if (User.Identity.IsAuthenticated)
            {
                var response = await _userService.GetUserByEmail(User.Identity.Name);

                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return PartialView(response.Data);
                }
                ModelState.AddModelError("Error", response.Description);
            }
            ModelState.AddModelError("Error", "You are not authenticated");
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> Update(User user)
        {
            if (ModelState.IsValid)
            {
                await _userService.UpdateUser(user.Id_user, user);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

Webstore/Views/User/Login.cshtml
@model Webstore.Domain.ViewModel.User.LoginViewModel

@{
    Layout = "_Layout";
    ViewData["Title"] = "Login";
}

<div>
    <div>
        <h1>Authorization</h1>
        <form autocomplete="on" method="post" asp-controller="User" asp-action="Login">
            <div asp-validation-summary="All" class="text-danger text-left"></div>
            <label>Email: </label><br />
            <input asp-for="Email" placeholder="Email" class="form-control textbox-dg font-weight-bold text-center" type="text">
            <label>Password: </label><br />
            <input autocomplete="new-password" asp-for="Password" placeholder="Password" class="form-control textbox-dg font-weight-bold text-center" type="password"><br/>
            <button class="btn btn-success btn-lg float-right">Login</button><br/>
            Account not created yet? <a asp-controller="User" asp-action="Register" >Registration</a>
        </form>
    </div>
</div>

Webstore/Views/User/Register.cshtml
@model Webstore.Domain.ViewModel.User.RegisterViewModel

@{
    Layout = "_Layout";
    ViewData["Title"] = "Registration";
}

<h1>Регистрация</h1>
<hr />
<form asp-controller="User" asp-action="Register">
    <div asp-validation-summary="All" class="text-danger text-left"></div>
    <div>
        <label>Name:</label>
        <div>
            <input asp-for="FirstName" placeholder="Ivan" type="text" required/>
        </div>
    </div>
    <div>
        <label>Last name:</label>
        <div>
            <input asp-for="LastName" placeholder="Vasilyev" type="text" required/>
        </div>
    </div>
    <div>
        <label>Middle name:</label>
        <div>
            <input asp-for="MiddleName" placeholder="Anatolyevich" type="text" required/>
        </div>
    </div>
    <div>
        <label>Password:</label>
        <div>
            <input asp-for="Password" placeholder="********" minlength="8" type="password" required/>
        </div>
    </div>
    <div>
        <label>Confirm password:</label>
        <div>
            <input asp-for="PasswordConfirm" placeholder="********" minlength="6" type="password" required/>
        </div>
    </div>
    <div>
        <label>Email:</label>
        <div>
            <input asp-for="Email" placeholder="example@mail.ru" type="email" required/>
        </div>
    </div>
    <div>
        <label>Phone:</label>
        <div>
            <input asp-for="Phone" placeholder="+78005553535" type="number" required/>
        </div>
    </div>
    <div>
        <label>Возраст</label>
        <div>
            <input asp-for="Age" placeholder="25" min="18" max="65" type="number" required/>
        </div>
    </div>
    <br />
    <button class="btn btn-success btn-lg float-right" type="submit">Register</button><br/>
    Account created yet? <a asp-controller="User" asp-action="Login" >Login</a>
</form>

Webstore/Views/User/Update.cshtml
@using Webstore.Domain.Enum
@model Webstore.Domain.Entity.User
@{
    Layout = "_Layout";
}
<h1>Update user</h1>
<hr />
<form asp-controller="User" asp-action="Update" enctype="multipart/form-data">

    <input asp-for="@Model.Id_user" hidden>
    <input asp-for="@Model.Orders" hidden>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div>
        <label asp-for="@Model.FirstName" class="col-form-label"></label>
        <input type="text" class="form-control" asp-for="@Model.FirstName">
    </div>
    <div>
        <label asp-for="@Model.MiddleName" class="col-form-label"></label>
        <input type="text" class="form-control" asp-for="@Model.MiddleName">
    </div>
    <div>
        <label asp-for="@Model.LastName" class="col-form-label"></label>
        <input type="text" class="form-control" asp-for="@Model.LastName">
    </div>
    <div>
        <label asp-for="@Model.Age" class="col-form-label"></label>
        <input type="text" class="form-control" asp-for="@Model.Age">
    </div>
    <div>
        <label asp-for="@Model.Phone" class="col-form-label"></label>
        <input type="text" class="form-control" asp-for="@Model.Phone">
    </div>
     <div>
        <label asp-for="@Model.Password" class="col-form-label"></label>
        <input type="password" class="form-control" asp-for="@Model.Password">
    </div>
    <div>
        <label asp-for="@Model.Email" class="col-form-label"></label>
        <input type="text" class="form-control" asp-for="@Model.Email">
    </div>
    @if (User.IsInRole("Admin"))
    {
        <div>
            <label asp-for="@Model.Role" class="col-form-label"></label>
            <input type="number" min=0 max=1 value="0" class="form-control" asp-for="@Model.Role">
        </div>
    }
    <br />
    <button class="btn btn-success btn-lg float-right" type="submit">Save</button><br />
</form>
<br />
<a class="btn btn-dark" asp-controller="Product" asp-action="ReadProducts">Back to the store</a>