Webstore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Webstore.DAL;
using Webstore.Domain.Entity;
using Webstore.Domain.Helper;
using Webstore.Domain.ViewModel.Cart;
using Webstore.Service.Interfaces;

namespace Webstore.Controllers
{
    public class CartController : Controller
    {
        public List<Item> items { get; set; }
        public decimal total { get; set; }

        private readonly ApplicationDbContext _context;
        public CartController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(CartViewModel model)
        {
            return View();
        }

        public IActionResult Init()
        {
            if (User.Identity.IsAuthenticated)
            {
                items = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                if (items != null)
                {
                    total = items.Sum(i => i.Product.Price * i.Quantity);
                }
            }
            else
            {
                items = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                for (var i = 0; i < items.Count; i++)
                {
                    items.RemoveAt(i);
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", items);
            }
            return View("Index", new CartViewModel(items, total));
        }
        [HttpPost]
        public IActionResult AddToCart(Guid id_product, int quantity)
        {
            try
            {
                Product product = _context.Product.FirstOrDefault(x => x.Id_product == id_product && x.Quantity >= 1);
                items = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                if (product == null || product.Quantity <= 0)
                {
                    return View("Error", $"This item is out of stock");
                }
                else
                {
                    if (items == null)
                    {
                        items = new List<Item>();
                        items.Add(new Item
                        {
                            Product = product,
                            Quantity = quantity
                        });
                        SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", items);
                    }
                    else
                    {
                        int index = Exists(items, id_product);
                        if (index == -1)
                        {
                            items.Add(new Item
                            {
                                Product = product,
                                Quantity = quantity
                            });
                        }
                        else if (quantity <= product.Quantity && (items[index].Quantity + quantity <= product.Quantity))
                        {
                            items[index].Quantity += quantity;
                        }
                        else
                        {
                            items[index].Quantity += product.Quantity - quantity;
                        }
                        SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", items);
                    }
                }
                return RedirectToAction("ReadProducts", "Product");
            }
            catch (Exception ex)
            {
                return View("Error", $"This product is no longer available");
            }
        }

        public IActionResult DeleteFromCart(Guid id_product)
        {
            items = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = Exists(items, id_product);
            items.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", items);
            return RedirectToAction("Init");
        }

        public IActionResult Update(int[] quantities)
        {
            items = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (var i = 0; i < items.Count; i++)
            {
                items[i].Quantity = quantities[i];
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", items);
            return RedirectToAction("Init");
        }

        public IActionResult CreateOrder()
        {
            try
            {
                items = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");

                User user = _context.User.FirstOrDefault(x => x.Email == (User.Identity.Name));

                DateTime date = DateTime.Now;

                Order order = Order.OrderConstr(user.Id_user, date);
                _context.Add(order);
                _context.SaveChanges();
                Guid id_order = order.IdOrder;
                for (var i = 0; i < items.Count; i++)
                {
                    try
                    {
                        Product? productBd = _context.Product.FirstOrDefault(x => x.Id_product == items[i].Product.Id_product && x.Quantity >= 1);
                        if (productBd != null && (productBd.Quantity - items[i].Quantity) >= 0)
                        {
                            Guid id_product = productBd.Id_product;
                            int quantity = items[i].Quantity;
                            decimal pricePerUnit = productBd.Price;
                            OrderProduct orderProduct = new(id_order, id_product, quantity, pricePerUnit);
                            _context.Add(orderProduct);
                            _context.SaveChanges();

                            productBd.Quantity -= items[i].Quantity;
                            _context.Update(productBd);
                            _context.SaveChanges();
                        }
                        else
                        {
                            String errors = "";
                            _context.Order.Remove(order);
                            errors += productBd.Title + ", ";
                            return View("Error", $"These products are no longer available: {errors}, but the available items are purchased");
                        }
                    }
                    catch (Exception ex)
                    {
                        return View("Error", $"{ex}");
                    }
                }
                for (var i = 0; i < items.Count; i++)
                {
                    items.RemoveAt(i);
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", items);
                return RedirectToAction("ReadProducts", "Product");
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }

        }

        private int Exists(List<Item> cart, Guid id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id_product == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

Webstore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Webstore.Service.Interfaces;

namespace Webstore.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        [HttpGet]
        public IActionResult ReadOrders()
        {
            var response = _orderService.ReadOrders();

            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            return View("Error", $"{response.Description}");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteOrder(Guid id)
        {
            var response = await _orderService.DeleteOrder(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return RedirectToAction("ReadOrders");
            }
            return View("Error", $"{response.Description}");
        }
    }
}

Webstore/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Webstore.Domain.Entity;
using Webstore.Domain.Helper;
using Webstore.Domain.ViewModel.User;
using Webstore.Service.Interfaces;

namespace Webstore.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Register() => View();

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _userService.Register(model);
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(response.Data));

                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("Error", response.Description);
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Login() => View();

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _userService.Login(model);
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(response.Data));
                    List<Item> items = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                    for (var i = 0; i < items?.Count; i++)
                    {
                        items.RemoveAt(i);
                    }
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", items);
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("Error", response.Description);
            }
            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            List<Item> items = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (var i = 0; i < items?.Count; i++)
            {
                items.RemoveAt(i);
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", items);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Update()
        {
            if (User.Identity.IsAuthenticated)
            {
                var response = await _userService.GetUserByEmail(User.Identity.Name);

                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return PartialView(response.Data);
                }
                ModelState.AddModelError("Error", response.Description);
            }
            ModelState.AddModelError("Error", "You are not authenticated");
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> Update(User user)
        {
            if (ModelState.IsValid)
            {
                await _userService.UpdateUser(user.Id_user, user);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

Webstore/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Webstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Webstore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Webstore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="ReadProducts">Store</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Register">Registration</a>
                            </li> 
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (!User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Cart" asp-action="Init">Cart</a>
                                </li>
                            }
                            else if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Order" asp-action="ReadOrders">List of orders</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Update">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-danger" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Rud Daniil, SSTU, б2-ИФСТ-21, 2022 - Webstore
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>